const obfuscatedMap = {
  "zfw95t": "BQADAQAD6QsAAkc8wETPBbq7aUPIcRYE",
  "agfuq4": "BQADAQAD4AwAAkc8wES4NlhcULH6SxYE",
  "79d005": "BQADAQADOg0AAkc8wERlEmDkXfexsBYE",
  "hohm7h": "BQADAQADeg0AAkc8wESW5dikEL01KxYE",
  "uldame": "BQADAQADlA0AAkc8wETPNSRyK0kejhYE",
  "5u60ei": "BQADAQADtA4AAkc8wETnsTYc5QABtWgWBA",
  "xujdfi": "BQADAQADwQ4AAkc8wESVIsG6TpsNlRYE",
  "dk067y": "BQADAQADGBMAAkc8wERkzdVGRhb9fRYE",
  "7do2n6": "BQADAQADRBMAAkc8wERfZTVfjpuIIhYE",
  "a61mhw": "BQADAQADAgsAAkc8yESQZs7iqSmIaBYE",
  "ar5et4": "BQADAQADCAsAAkc8yEQaETw6JG_jAhYE",
  "gm0qqf": "BQADAQADFQsAAkc8yETFVaFuKt-LqhYE",
  "hfwfpp": "BQADAQADHAsAAkc8yETMQVX_i47PzhYE",
  "5j6clz": "BQADAQADJwsAAkc8yER9HjUd9K_WvBYE",
  "4e41hz": "BQADAQADYgsAAkc8yESVL76G9-RBvRYE"
};